version: '3.8'

name: api-sandbox
services:
  app:
    build: .
    container_name: app
    ports:
      - 8080:${APP_PORT}
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_APP_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_APP_PASSWORD}
    depends_on:
      - postgres
    networks:
      - sb-net

  postgres:
    image: postgres:17-alpine
    container_name: db
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - sb-data:/var/lib/postgresql/data
#      - ./_entrypoint:/docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Bangkok
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_APP_USER=${POSTGRES_APP_USER}
      - POSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD}
    networks:
      - sb-net
volumes:
  sb-data:
networks:
  sb-net: